[package]
name = "jevscript-ir"
description = "The versioned Jevscript intermediate representation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
jevscript-syntax.workspace = true
hex.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[[example]]
name = "schema"
path = "examples/schema.rs"
